AWSTemplateFormatVersion: '2010-09-09'
Description: Configures parameters for VPC supernets
Parameters:
  SsmPrefix:
    Description: The prefix portion to use for SSM parameters
    Type: String
  SupernetNames:
    Description: Friendly names for the subnet groups
    Type: CommaDelimitedList
  TotalSupernets:
    Description: The total number of subnet groups
    Type: AWS::SSM::Parameter::Value<String>
  VpcCidr:
    Description: Cidr of the VPC network
    Type: String
  VpcMask:
    Description: The mask portion of the VPC cidr
    Type: Number
Conditions:
  TotalSupernets2: !Or [!Equals [!Ref 'TotalSupernets', '2'], !Condition 'TotalSupernets3']
  TotalSupernets3: !Or [!Equals [!Ref 'TotalSupernets', '3'], !Condition 'TotalSupernets4']
  TotalSupernets4: !Equals [!Ref 'TotalSupernets', '4']
Mappings:
  CidrBits:
    "28": {"1":  '4'}
    "27": {"1":  '5', "2":  '4'}
    "26": {"1":  '6', "2":  '5', "3":  '4', "4":  '4'}
    "25": {"1":  '7', "2":  '6', "3":  '5', "4":  '5', "5":  '4', "6":  '4', "7":  '4', "8":  '4'}
    "24": {"1":  '8', "2":  '7', "3":  '6', "4":  '6', "5":  '5', "6":  '5', "7":  '5', "8":  '5'}
    "23": {"1":  '9', "2":  '8', "3":  '7', "4":  '7', "5":  '6', "6":  '6', "7":  '6', "8":  '6'}
    "22": {"1": '10', "2":  '9', "3":  '8', "4":  '8', "5":  '7', "6":  '7', "7":  '7', "8":  '7'}
    "21": {"1": '11', "2": '10', "3":  '9', "4":  '9', "5":  '8', "6":  '8', "7":  '8', "8":  '8'}
    "20": {"1": '12', "2": '11', "3": '10', "4": '10', "5":  '9', "6":  '9', "7":  '9', "8":  '9'}
    "19": {"1": '13', "2": '12', "3": '11', "4": '11', "5": '10', "6": '10', "7": '10', "8": '10'}
    "18": {"1": '14', "2": '13', "3": '12', "4": '12', "5": '11', "6": '11', "7": '11', "8": '11'}
    "17": {"1": '15', "2": '14', "3": '13', "4": '13', "5": '12', "6": '12', "7": '12', "8": '12'}
    "16": {"1": '16', "2": '15', "3": '14', "4": '14', "5": '13', "6": '13', "7": '13', "8": '13'}
Resources:
  ParameterSupernetCidrs:
    Type: AWS::SSM::Parameter
    Properties:
      Description: List of supernet CIDR blocks
      Name: !Sub '${SsmPrefix}/supernets/cidrs'
      Type: StringList
      Value: !Join [',', !Cidr [!Ref 'VpcCidr', !Ref 'TotalSupernets', !FindInMap [CidrBits, !Ref 'VpcMask', !Ref 'TotalSupernets']]]
  ParameterSupernet1Cidr:
    Type: AWS::SSM::Parameter
    Properties:
      Description: CIDR of the supernet
      Name: !Sub
        - '${SsmPrefix}/supernets/${SupernetName}/cidr'
        - SupernetName: !Select ['0', !Ref 'SupernetNames']
      Type: String
      Value: !Select ['0', !Split [',', !GetAtt 'ParameterSupernetCidrs.Value']]
  ParameterSupernet2Cidr:
    Type: AWS::SSM::Parameter
    Condition: TotalSupernets2
    Properties:
      Description: CIDR of the supernet
      Name: !Sub
        - '${SsmPrefix}/supernets/${SupernetName}/cidr'
        - SupernetName: !Select ['1', !Ref 'SupernetNames']
      Type: String
      Value: !Select ['1', !Split [',', !GetAtt 'ParameterSupernetCidrs.Value']]
  ParameterSupernet3Cidr:
    Type: AWS::SSM::Parameter
    Condition: TotalSupernets3
    Properties:
      Description: CIDR of the supernet
      Name: !Sub
        - '${SsmPrefix}/supernets/${SupernetName}/cidr'
        - SupernetName: !Select ['2', !Ref 'SupernetNames']
      Type: String
      Value: !Select ['2', !Split [',', !GetAtt 'ParameterSupernetCidrs.Value']]
  ParameterSupernet4Cidr:
    Type: AWS::SSM::Parameter
    Condition: TotalSupernets4
    Properties:
      Description: CIDR of the supernet
      Name: !Sub
        - '${SsmPrefix}/supernets/${SupernetName}/cidr'
        - SupernetName: !Select ['3', !Ref 'SupernetNames']
      Type: String
      Value: !Select ['3', !Split [',', !GetAtt 'ParameterSupernetCidrs.Value']]
Outputs:
  ParameterSupernetCidrs:
    Description: Systems Manager parameter containing the supernet CIDR blocks
    Value: !Ref 'ParameterSupernetCidrs'
  Supernet1Cidr:
    Description: Mask portion of the network for supernet 1
    Value: !GetAtt 'ParameterSupernet1Cidr.Value'
  Supernet2Cidr:
    Description: Mask portion of the network for supernet 2
    Value: !If [TotalSupernets2, !GetAtt 'ParameterSupernet2Cidr.Value', 'null']
  Supernet3Cidr:
    Description: Mask portion of the network for supernet 3
    Value: !If [TotalSupernets3, !GetAtt 'ParameterSupernet3Cidr.Value', 'null']
  Supernet4Cidr:
    Description: Mask portion of the network for supernet 4
    Value: !If [TotalSupernets4, !GetAtt 'ParameterSupernet4Cidr.Value', 'null']