# Deployment wide parameters
# NOTE:THIS FILE HAS BEEN UPDATED TO REFLECT THE NEW RBN ALT ACCOUNT
global:
  region: us-east-1
  release: development
  sync_base: ./
  sync_dirs: [
    'cloudformation',
    'bootstrap'
  ]
  sync_exclude: [
    '.swp',
    '.git',
    '.DS_Store',
    '/chef/',
    'README.md'
  ]
  sync_dest_bucket: rbn-ops-us-east-1
  template_bucket: rbn-ops-us-east-1
  tags:
    Project: ALT-220
    Environment: Dev
    Release : development
  CloudToolsBucket: rbn-ops-us-east-1

Network:
  release: development
  stack_name: RBN-Ops-Network
  sync_base: ./
  sync_dirs: [
    'cloudformation',
    'builds',
    'lambda'
  ]
  lambda_dirs: [
    'lambda/attach_hosted_zone',
    'lambda/number_azs',
    'lambda/peer',
    'lambda/subnets',
    'lambda/vpc_cidr'
  ]
  template: cloudformation/network/vpc/top.json 
  parameters:
    Project: ALT-220
    SSLCertId: ""
    CommonBootstrapFile: common.sh
    PrivateDomain: awsinternal.ops.rightbrainnetworks.com
    PublicDomain: 'ops.rightbrainnetworks.com'
    InternalHostedZone: Z3BSTGMXUCYSV7
    Environment: Test
    VPNCIDR: "10.0.0.0/8"
    GlobalCIDR: "10.0.0.0/8"
    ReservedCidrs: ""
    MaskBit: "22"
    # This bastion from is the RBN Office
    BastionSSHFrom: "50.241.213.107/32" 
    EC2KeyPair: bastion-us-east-1
    BastionInstanceType: t2.nano
    BastionAMI: ami-0b33d91d
    CloudToolsBucket: rbn-ops-us-east-1


ECSCluster:
  release: develop
  stack_name: RBN-Ops-ECS-Cluster
  template_bucket: rbn-ops-us-east-1
  template: cloudformation/ecs-cluster/top.json
  lambda_dirs: []
  parameters:
    Environment: Dev
    Role: ECS-Cluster
    EC2KeyPair: common-us-east-1
    AMI: ami-8f7687e2
    LogHost: ""
    CloudToolsBucket: rbn-ops-us-east-1
  lookup_parameters:
    VPC: {Stack: Network, OutputKey: VPC}
    VPCCIDR: {Stack: Network, OutputKey: VPCCIDR}
    PublicSubnetList: {Stack: Network, OutputKey: PublicSubnets}
    PrivateSubnetList: {Stack: Network, OutputKey: PrivateSubnets}