name: deploy
on:
  release:
    type: [ published ]
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/deployer.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'deployer'
  SELF_SEMVER_TAG: "master"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
    printJob:
      name: Print event
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"
    build:
        runs-on: ubuntu-latest
        outputs:
          RETURN_STATUS: ${{ steps['semver']['outputs']['RETURN_STATUS'] }}
          SEMVER_NEW_VERSION: ${{ steps['semver']['outputs']['SEMVER_NEW_VERSION'] }}
          VERSION: ${{ steps['semver']['outputs']['VERSION'] }}
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: ${{ env.GITHUB_REF }}
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: debug
          run: |
            tree -d
#        - name: Set Up Git Config
#          run: |
#            git config user.name "GitHub Actions Bot"
#            git config user.email "<>"
#        - name: Run Auto-Semver
#          id: semver
#          if: github.event_name != 'release'
#          uses: RightBrain-Networks/semver-action@1.0-beta
#          with:
#            mode: get
#        - name: Install dependencies
#          run: |
#            python -m pip install --upgrade pip
#            pip install -r requirements.txt
#        - name: build
#          run: |
#            python setup.py sdist
#        - name: test
#          run: |
#            python tests.py
#          working-directory: deployer