name: deployer-actions
on: [push]
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/deployer.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'deployer'
  SELF_SEMVER_TAG: "master"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: ${{ env.GITHUB_REF }}
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Set Up Git Config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        - name: Run Auto-Semver
          id: semver
          uses: RightBrain-Networks/semver-action@1.0-beta
          with:
            mode: set
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: build
          run: |
            python setup.py sdist
        - name: test
          run: |
            python tests.py
          working-directory: deployer
    CheckVersion:
        runs-on: ubuntu-latest
        needs: build
        outputs:
          RETURN_STATUS: steps['semver']['outputs']['RETURN_STATUS']
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set Up Git Config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        - name: Run Auto-Semver
          id: semver
          uses: RightBrain-Networks/semver-action@1.0-beta
          with:
            mode: set
    release:
        runs-on: ubuntu-latest
        needs: [CheckVersion, build]
        if: needs.CheckVersion.outputs.RETURN_STATUS == ''
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
              ref: ${{ env.GITHUB_REF }}
          - name: Set Up Git Config
            run: |
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
          - name: Run Auto-Semver
            id: semver
            uses: RightBrain-Networks/semver-action@1.0-beta
            with:
              mode: set
          - name: Create Release
            uses: actions/create-release@v1
            if: steps['semver']['outputs']['RETURN_STATUS'] == ''
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
              release_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
              body: Version ${{ steps.semver.outputs.SEMVER_NEW_VERSION }} released automatically by [RightBrain-Networks/auto-semver](https://github.com/RightBrain-Networks/auto-semver)
              draft: false
              prerelease: false