name: release
on:
  release:
    types:
      - published
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/deployer.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'deployer'
  SELF_SEMVER_TAG: "master"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifact
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          run: |
            WF_NAME="build"
            ARTIFACT_NAME="deployer-${{ github.ref_name }}.tgz"
            RUN_ID=`gh run list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
            gh run download ${RUN_ID} -n ${ARTIFACT_NAME}
        - name: Debug
          run: |
            pwd
            tree -d
#        - name: Set up Python 3.7
#          uses: actions/setup-python@v1
#          with:
#            python-version: 3.7
#        - name: Set Up Git Config
#          run: |
#            git config user.name "GitHub Actions Bot"
#            git config user.email "<>"
#        - name: Run Auto-Semver
#          id: semver
#          uses: RightBrain-Networks/semver-action@1.0-beta
#          with:
#            mode: get