#name: release
#on:
#  create:
#    tags:
#      - "[0-9]+.[0-9]+"
#env:
#  GITHUB_URL: 'git@github.com:RightBrain-Networks/deployer.git'
#  GITHUB_KEY: 'rbn-ops github'
#
#  SERVICE: 'deployer'
#  SELF_SEMVER_TAG: "master"
#
#  AWS_DEFAULT_REGION: "us-east-1"
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#jobs:
#    printJob:
#      name: Print event
#      runs-on: ubuntu-latest
#      steps:
#        - name: Dump GitHub context
#          env:
#            GITHUB_CONTEXT: ${{ toJson(github) }}
#          run: |
#            echo "$GITHUB_CONTEXT"
#    release:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#          with:
#            fetch-depth: 0
#            ref: ${{ env.GITHUB_REF }}
#        - name: Set up Python 3.7
#          uses: actions/setup-python@v1
#          with:
#            python-version: 3.7
#        - name: Run Auto-Semver
#          id: semver
#          uses: RightBrain-Networks/semver-action@1.0-beta
#          with:
#            mode: get
#        - name: Create Release
#          if: steps['semver']['outputs']['RETURN_STATUS'] == ''
#          uses: actions/create-release@v1
#          env:
#            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#          with:
#            tag_name: ${{ steps['semver']['outputs']['VERSION'] }}
#            release_name: ${{ steps['semver']['outputs']['VERSION'] }}
#            body: Version ${{ steps['semver']['outputs']['VERSION'] }} released automatically by [RightBrain-Networks/auto-semver](https://github.com/RightBrain-Networks/auto-semver)
#            draft: false
#            prerelease: false